### ISSUE TITLE
devless.io has expired SSL cert

### ISSUE THREAD

**Issue by cweagans** [DevlessTeam/devlessteam.github.io#1]
https://devless.io is broken because of an expired cert. Not sure where is the appropriate place to report this, but here seemed as good a place as any.

**Comment by EDDYMENS** [comment]
It came to our notice after the certificate update failed . We will resolve this ASAP . Thanks 👍

**Comment by EDDYMENS** [comment]
@cweagans all SSL  issues have been resolved
